# Name of your application. Used to uniquely configure containers.
service: tunehoard

# Name of the container image.
image: vectorbox/tunehoard

# Deploy to these servers.
servers:
  web:
    - 159.203.118.126

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: tunehoard.com

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: registry.digitalocean.com
  username: miha@rebernik.info

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - DO_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - BOT_TOKEN
    - YOUTUBE_API_KEY
    - SPOTIFY_CLIENT_ID
    - SPOTIFY_CLIENT_SECRET
  clear:
    PORT: 80
    SERVER_PROTOCOL: https
    SERVER_HOST: tunehoard.com

# Use a persistent storage volume.
#
volumes:
  - "tunehoard_storage:/app/storage"
